# Generated by Django 2.2 on 2022-03-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20220306_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='number_money',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма перевода'),
        ),
    ]
