# Generated by Django 2.2 on 2022-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_auto_20220307_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='number_money',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
