# Generated by Django 2.2 on 2022-03-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_auto_20220307_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='number_money',
            field=models.IntegerField(default=None, null=True, verbose_name='Количество'),
        ),
    ]
