# Generated by Django 2.2 on 2022-03-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_auto_20220308_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус исполнения'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус исполнения'),
        ),
    ]
